### PR TITLE
refactor(mercury): introduce CachedObjectInfo for better clarity…

### PR DESCRIPTION
**Pull request by el-ev**
… and memory efficiency

1. No `CachedObject` utilized all their fields, so we'd better fold some with a tagged union. It looks better on my machine. As for "memory efficiency", no real world impact though.
2. `generate_temp_path()` is called many times with same arguments in `get_fallback()`, could be reduced to one.
3. `SHA1::new()` now accepts `&[u8]` instead of `&Vec<u8>`, providing more flexibility.

### CODE REVIEW

**Comment by el-ev** [comment]
those `.as_bytes().to_vec()`s are insane...
image

**Review by MrBeanCpp — APPROVED** [review]
It looks good, although I prefer the name `CachedObjectInner`.

**Comment by el-ev** [comment]
> It looks good, although I prefer the name `CachedObjectInner`.

I disagree.
1) It is `pub`.
2) If a `struct` is named `FooInner`, usually it means some critical implementation of `Foo` is delegated to the inner. But this `enum` is just a carrier of information.

edit:
It doesn't necessarily have to be `pub`...
It should be called `CacheObjectInfo`, not sure where the extra 'd' came from.

**Review by genedna — APPROVED** [review]

**Comment by MrBeanCpp** [comment]
Wow, what a strict world. Maybe I should dance with shackles.

**Comment by el-ev** [comment]
@MrBeanCpp wdym by “dance with shackles” when you choose to write something in safe Rust?

**Comment by MrBeanCpp** [comment]
Perhaps what truly constrains us are not the rules written in black and white, in this world filled with carbon-based life.

**Comment by el-ev** [comment]
Don't you really find it annoying to change the **internal** implementation of a library but have to dig into the source code of five or six other projects to fix errors?

**Comment by el-ev** [comment]
I mean, you don't have to write codes like `std`, but at least take a look at [object.rs](https://github.com/GitoxideLabs/gitoxide/blob/main/gix-pack/src/cache/object.rs) to see what a project in the same black-and-white world is like.

**Pull request merged**
