### PR TITLE
refactor(mercury): optimize temp path generation

### PR DESCRIPTION
**Pull request by el-ev**
Depending on the platform, this pr reduces the time on the single function `generate_temp_path` by half (0.30% -> 0.15%) to 3/4 (~2% -> ~0.5%).

1. Preallocate enough space for `PathBuf` to prevent expensive reallocation which once happened every time.
2. Call `_to_string()` only once. I expected this optimization to be done by the compiler, but it appears not.
3. Replace `to_string()` by `_to_string()`. I don't like this hack very much, but it's 50% faster.

### CODE REVIEW

**Comment by Hou-Xiaoxuan** [comment]
@el-ev  Amazing, 50% faster! I’m curious about how you tested it. I’d love to measure it on my own machine as well.

**Comment by el-ev** [comment]
> @el-ev Amazing, 50% faster! I’m curious about how you tested it. I’d love to measure it on my own machine as well.

I tested it in `test_decode_large_file_stream` with `cargo flamegraph --unit-test mercury --root -r -- test_decode_large_file_stream`. The actual performance may vary, but you can see the large `realloc` part eliminated.
[cargo flamegraph](https://github.com/flamegraph-rs/flamegraph)

| before| after |
| -------- | ------- |
|image | image   |

**Comment by el-ev** [comment]
Maybe you are referring to the `_to_string()`? It is shown as such on my device.
image

**Comment by MrBeanCpp** [comment]
In **Release** mode, is there still such a performance difference between `_to_string()` and `to_string()`?

**Comment by el-ev** [comment]
> In **Release** mode, is there still such a performance difference between `_to_string()` and `to_string()`?

```
cargo flamegraph --unit-test mercury --root -r -- test_decode_large_file_stream
                                             ^
```


Of course I won't do profiling under debug mode...

**Comment by MrBeanCpp** [comment]
Amazing, but mass usage of `_to_string()` will become unbearable.

**Comment by Hou-Xiaoxuan** [comment]
Although I don’t know why, it is indeed much faster. I tested it with the following code, and the difference was particularly noticeable during the first execution.

```bash
 to_string first time : 5.717µs
_to_string first time: 221ns
 to_string second time: 230ns
_to_string second time: 166ns
 to_string first time : 170ns
_to_string first time: 154ns
 to_string second time: 248ns
_to_string second time: 209ns
 to_string 1000 times: 187.449µs
_to_string 1000 times: 163.898µs
```

test code
```rust
    #[test]
    fn test_performance_of_to_string() {
        let test_cases = [
        "8ab686eafeb1f44702738c8b0f24f2567c36da6d",
        "9ab686eafeb1f44702738c8b0f24f2567c36da6d",
    ];

    for &hash_str in &test_cases {
        let sha1 = SHA1::from_str(hash_str).unwrap();
        time_it!(" to_string first time ", { sha1.to_string(); });
        time_it!("_to_string first time", { sha1._to_string(); });
        time_it!(" to_string second time", { sha1.to_string(); });
        time_it!("_to_string second time", { sha1._to_string(); });
    }

    time_it!(" to_string 1000 times",  {
        for i in 0..1000 {
            let sha_temp = SHA1::new(&format!("{}", i).bytes().collect());
            sha_temp.to_string();
        }
    });
    time_it!("_to_string 1000 times", {
        for i in 0..1000 {
            let sha_temp = SHA1::new(&format!("{}", i).bytes().collect());
            sha_temp._to_string();
        }
    });
    }
```

**Review by Hou-Xiaoxuan — APPROVED** [review]

**Review by genedna — APPROVED** [review]

**Pull request merged**
